---
- hosts: workstation
  vars_files:
    - vars/main.yaml
  module_defaults:
    group/k8s:
      namespace: "{{ namespace }}"
      ca_cert: "/etc/pki/tls/certs/ca-bundle.crt"
      host: "{{ managed_cluster_host }}"
      kubeconfig: "{{ kubeconfig }}"
  roles:
    - secret_check_managed

